### ISSUE TITLE
[BUG] When using View menu, folders or images are shown on a single line

### ISSUE THREAD

**Issue by jonk999** [RupertAvery/DiffusionToolkit#211] opened 2024-02-10 07:05 UTC
**Describe the bug**
When using V1.6, if I select View, Folders or View, Albums when you select one, everything is on a single line rather than wrapping.

**Version:**
V1.6

**Tool:**
N/A

**To Reproduce**
As described in 'describe the bug'

**Expected behavior**
If selecting View, Folders or View, Albums then when clicking on a folder, pics in that folder, etc are shown in the next pane wrapped to fill the space.

**Affected Image(s)**
N/A

**Screenshots**
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27007377/195ec116-f039-46c7-8699-0da680996ddc)

**Comment by RupertAvery** [comment] 2024-02-10 11:47
What screen resolution do you have? I'm not able to reproduce this issue currently and will need more information.

**Comment by acorderob** [comment] 2024-02-10 12:49
I also have this problem. My main monitor resolution is 2560x1600, but it also happens in the second one at 1920x1080. Both are at 100% scale.

**Comment by RupertAvery** [comment] 2024-02-10 15:23
Can you check if this fixes the issue?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7855752123/artifacts/1235591850

**Comment by acorderob** [comment] 2024-02-10 21:55
Yes! It fixed it.

**Comment by jonk999** [comment] 2024-02-11 03:41
I'm using 2560x1440 at 100% scale. Can confirm the link provided fixes it for me also.

**Comment by Ariloum** [comment] 2024-02-12 00:06
> Can you check if this fixes the issue?
> 
> https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7855866422/artifacts/1235608381

looks like it fixed it for me too, 5120x1440 display at 150% scale

**Comment by RupertAvery** [comment] 2024-02-13 04:49
Fixed in the latest version (v1.6.1)

**Closed by RupertAvery** 2024-02-13 04:49 UTC
