### ISSUE TITLE
Chinese problem

### ISSUE THREAD

**Issue by xam0482** [RupertAvery/DiffusionToolkit#71] opened 2023-03-14 11:44 UTC
Prompt word in Chinese is garbled
Unable to find Chinese in filter

**Comment by RupertAvery** [comment] 2023-03-15 12:04
Please upload a sample image (PNG) with chinese prompt here, or paste the full prompt here so I can test, thanks

**Comment by RupertAvery** [comment] 2023-04-29 13:13
Looks like this issue is caused by a bug in the Metadata Extractor library. I will provide a fix in the next release (1.2)

**Comment by RupertAvery** [comment] 2023-10-01 06:35
Fix for this will be included in next release

**Closed by RupertAvery** 2023-10-01 06:35 UTC
Labels: bug
