### ISSUE TITLE
[BUG] (v1.5) Album image counts are incorrect

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#165] opened 2023-12-24 10:13 UTC
**Describe the bug**
The count seems to be always higher than it should. I believe it's because when you empty the recycle bin the images don't get removed from the AlbumImage table.

**Version:**
v1.5

**To Reproduce**
Add an image to an empty album.
Mark the image as deleted.
Empty the recycle bin.
Check album count.

**Expected behavior**
The count should be correct.

**Additional context**
You should have added foreign keys to your DB model. Now it's probably too late unless you fix the DB data before adding them.

**Comment by RupertAvery** [comment] 2023-12-24 14:42
Thanks. I'll fix this.  I can add a auto cleanup in the meantime for affected people on startup.

**Comment by RupertAvery** [comment] 2023-12-25 00:10
Never to late to fix DB issues :)

I've added a database migration system to handle future issues like this.

This latest version will run a script that will create a new AlbumImages table with foreign keys, and copy your AlbumImages to the new table, then rename them so that the new table is the current table. It won't delete the old table for now. This will run only once depending on the existence of a row corresponding to the script name in the Migration table.

The AlbumImage cleanup script to correct album counts will also be run once in the same way.

I've run this on my data with no issues, but if you can test this, I'd appreciate it!

It should, on run:

- Fix the album image countsm, i.e. `SELECT ImageId FROM AlbumImage WHERE ImageId NOT IN (SELECT Id FROM Image)` should return 0 rows
- Add FK constraints to the AlbumImage table
- Create an AlbumImageBackup table
- Remove entries from the AlbumImage when you Empty the Recycle Bin
- Update Album counts when you Empty the Recycle Bin
- Create a AlbumImage table with correct constraints if no table exists (such as on first run)

[Diffusion.Toolkit.v1.5.1.zip](https://github.com/RupertAvery/DiffusionToolkit/files/13763068/Diffusion.Toolkit.v1.5.1.zip)

Of course, make sure to backup your database just in case.

**Comment by acorderob** [comment] 2023-12-25 22:04
Unfortunately this version dies after adding "Opening database at..." in the log. The DB has a new empty Migration table but no other changes apparently. AlbumImage has no foreign keys and the counts are still wrong.

**Comment by RupertAvery** [comment] 2023-12-26 03:55
Thanks for testing. Looks like I need to sort the order of the scripts. I confirmed your issue after proper testing and this version should work now.

[Diffusion.Toolkit.v1.5.1.zip](https://github.com/RupertAvery/DiffusionToolkit/files/13768404/Diffusion.Toolkit.v1.5.1.zip)

**Comment by acorderob** [comment] 2023-12-26 09:48
Everything seems ok now. Invalid elements are removed, foreign keys added, and emptying recycle bin removes from AlbumImage. The only thing is that the backup of the table is done after removing the invalid elements, but i guess you will not make this backup in the final version. But if you do want to, i suggest you backup the entire DB with a meaningful filename before fixing anything.

BTW, another small detail you might want to fix: the horizontal splitter between image and metadata does not save its position.

**Comment by jonk999** [comment] 2023-12-29 00:10
@RupertAvery thanks for fixing this. Was just about to report the album image count issue.
Also would be great if the splitter between image and metadata could retain it's position if moved.
Cheers.

**Comment by RupertAvery** [comment] 2023-12-29 21:11
This should be fixed now, including splitter position

**Closed by RupertAvery** 2023-12-29 21:11 UTC
